apiVersion: v1
kind: PersistentVolume
metadata:
  name: jarvis-image-storage-pv
  labels:
    type: nfs-shared
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.160
    path: /stockage/system-storage/generated-images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarvis-image-storage-pvc
  namespace: jarvis-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: jarvis-image-storage-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jarvis-diffusers-cache-pv
  labels:
    type: nfs-shared
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.160
    path: /stockage/system-storage/diffusers-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarvis-diffusers-cache-pvc
  namespace: jarvis-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: jarvis-diffusers-cache-pv
  storageClassName: ""
