apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: jarvis-system
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: inference-engine
    app.kubernetes.io/part-of: jarvis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 60Gi
